name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest # Firefox in it
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - run: sudo apt-get install xvfb
      - run: npm install
      - run: DEBUG=eslint:cli-engine npm run lint:all
      - run: npm run build
      - run: xvfb-run --auto-servernum -- npm test
        env:
          CHROME_BIN: chromium-browser
      - run: cat */coverage/lcov.info
      - name: Coveralls SDK
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: sdk
          parallel: true
      - name: Coveralls Subscriptions
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: subscriptions
          parallel: true
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
